<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\workbench_annotation\Entity\WorkbenchAnnotationSeverity;

/**
 * Implements hook_page_attachments().
 */
function workbench_annotation_page_attachments(array &$page) {
  $user = \Drupal::currentUser();

  if (!$user->hasPermission('access workbench annotations')
    || \Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $page['#attached']['library'][] = 'workbench_annotation/main';

  $options = [];
  /** @var \Drupal\workbench_annotation\Entity\WorkbenchAnnotationSeverity[] $severities */
  $severities = WorkbenchAnnotationSeverity::loadMultiple();
  $options['default'] = [
    'id' => 'default',
    'severity_level' => 'default',
    'label' => 'Default',
  ];
  foreach ($severities as $severity_id => $severity) {
    $options[$severity_id] = [
      'id' => $severity->id(),
      'severity_level' => $severity->get('severity_level'),
      'label' => $severity->label(),
    ];
  }
  $page['#attached']['drupalSettings']['workbench_annotation'] = [
    'severities' => $options,
    'can_create' => $user->hasPermission('create workbench annotations'),
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function workbench_annotation_entity_view_alter(&$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $build['#cache']['contexts'][] = 'user.permissions';

  if (!_workbench_annotation_access($entity)) {
    return;
  }

  $build['#attributes']['data-workbench-annotation-entity-id'] = $entity->getEntityTypeId() . '/' . $entity->id();
}

/**
 * Access callback to determine if an Entity can be annotated.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The Entity to check.
 *
 * @return bool
 *   TRUE if the current user can access the Entity, FALSE otherwise.
 */
function _workbench_annotation_access(EntityInterface $entity) {
  /** @var \Drupal\workbench_moderation\ModerationInformation $workbench_information */
  $workbench_information = \Drupal::service('workbench_moderation.moderation_information');

  // Check if this is the latest moderated revision and if the user has access.
  return \Drupal::currentUser()->hasPermission('access workbench annotations')
  && $workbench_information->isModeratableEntity($entity)
  && $workbench_information->isLatestRevision($entity)
  && !$entity->isNew();
}

/**
 * Implements hook_annotation_entity_bundle_field_info_alter().
 */
function workbench_annotation_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  /** @var \Drupal\workbench_moderation\ModerationInformation $workbench_information */
  $workbench_information = \Drupal::service('workbench_moderation.moderation_information');

  if ($workbench_information->isModeratableBundle($entity_type, $bundle) && !empty($fields['moderation_state'])) {
    $fields['moderation_state']->addConstraint('ModerationAnnotation', []);
  }
}
